server:
  port: 8083

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        corsConfiguration:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "Content-Type"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
          filters:
            - RewritePath=/api/(?<path>.*), /$\{path}
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/reviews/**
          filters:
            - RewritePath=/api/(?<path>.*), /$\{path}
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**
          filters:
            - RewritePath=/api/(?<path>.*), /$\{path}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/